set -g default-terminal "screen-256color"

set -s escape-time 10
set -sg repeat-time 600
set -s focus-events on

set -q -g status-utf8 on
set -g history-limit 5000

set -g base-index 1

set -g renumber-windows on

set -g set-titles on

set -g display-panes-time 800
set -g display-time 1000
set -g status-interval 10

set -g monitor-activity on
set -g visual-activity off

set -g pane-border-style 'fg=black'
set -g status-style 'fg=white,bg=black'
set -g window-status-current-style 'bg=black,fg=white'

set -g mouse on

# Start new windows and panes in the active pane's current directory.
bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"
